version: '3.8'

services:
  nemogpt2-chatbot:
    build: .
    container_name: nemogpt2-chatbot
    volumes:
      - ./data:/workspace/data
      - ./scripts:/workspace/scripts
      - ./models:/workspace/models
    stdin_open: true
    tty: true
    environment:
      - MODEL_DIR=/workspace/models
    command: ["bash", "-c", "python /workspace/src/menu.py"]

